name: ansible-lint
on:
  push:
    branches: ["main"]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.1.3
